export const GET_ALL_USERS = 'GET_ALL_USERS';
export const SEND_NOTIFICATION_MODEL = 'SEND_NOTIFICATION_MODEL';
export const SHOW_NOTIFICATION_MODEL = 'SHOW_NOTIFICATION_MODEL';
export const SHOW_INVITATION_MODEL = 'SHOW_INVITATION_MODEL';
export const CANCEL_SEND_REQUEST = 'CANCEL_SEND_REQUEST'