export const ADD_GROUP_ACTION = 'ADD_GROUP_ACTION';
export const SELECT_GROUP_PERSON = 'SELECT_GROUP_PERSON';
export const REMOVE_GROUP_PERSON = 'REMOVE_GROUP_PERSON';
export const ADD_GROUP_BY_NAME = 'ADD_GROUP_BY_NAME';
export const BACK_TO_CONTACT = 'BACK_TO_CONTACT';
export const GET_TEAM_BY_ID = 'GET_TEAM_BY_ID'